package worker

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"syscall"
	"time"

	"github.com/cluster-os/node/internal/roles"
	"github.com/cluster-os/node/internal/services/slurm/auth"
	"github.com/sirupsen/logrus"
)

// SLURMWorker manages the slurmd daemon on worker nodes.
// All required data (controllerIP, mungeKey, nodeIP) are passed at construction
// by the phase machine — no cluster-state lookups, no retry loops.
type SLURMWorker struct {
	*roles.BaseRole
	controllerIP    string
	mungeKey        []byte
	nodeIP          string
	slurmdCmd       *exec.Cmd
	mungeKeyManager *auth.MungeKeyManager
}

// NewSLURMWorkerRole creates a worker with explicit connection parameters.
func NewSLURMWorkerRole(controllerIP string, mungeKey []byte, nodeIP string, logger *logrus.Logger) *SLURMWorker {
	return &SLURMWorker{
		BaseRole:        roles.NewBaseRole("slurm-worker", logger),
		controllerIP:    controllerIP,
		mungeKey:        mungeKey,
		nodeIP:          nodeIP,
		mungeKeyManager: auth.NewMungeKeyManager(logger),
	}
}

// Start sets up munge, writes a client-only slurm.conf, and starts slurmd.
// slurmd uses --conf-server to fetch its full config from slurmctld, so
// NodeName/partition entries do not need to be in the local file.
// Called once by the phase machine after munge key is received from leader.
func (sw *SLURMWorker) Start() error {
	sw.Logger().Infof("Starting SLURM worker (controller=%s)", sw.controllerIP)

	for _, dir := range []string{
		"/etc/slurm",
		"/var/lib/slurm/slurmd",
		"/var/log/slurm",
	} {
		os.MkdirAll(dir, 0755)
	}

	if err := sw.mungeKeyManager.WriteMungeKey(sw.mungeKey); err != nil {
		return fmt.Errorf("write munge key: %w", err)
	}

	if err := sw.mungeKeyManager.StartMungeDaemon(); err != nil {
		return fmt.Errorf("start munge: %w", err)
	}

	// Write a minimal slurm.conf for CLIENT tools (squeue, sbatch, sinfo) only.
	// slurmd itself fetches its full config from the controller via --conf-server.
	if err := sw.writeClientConfig(); err != nil {
		return fmt.Errorf("write slurm client config: %w", err)
	}

	if err := sw.startSlurmd(); err != nil {
		return fmt.Errorf("start slurmd: %w", err)
	}

	sw.SetRunning(true)
	return nil
}

// Stop stops slurmd
func (sw *SLURMWorker) Stop(ctx context.Context) error {
	sw.Logger().Info("Stopping SLURM worker")
	return sw.stopSlurmd()
}

// HealthCheck verifies slurmd is alive, restarting if needed
func (sw *SLURMWorker) HealthCheck() error {
	if sw.slurmdCmd == nil || sw.slurmdCmd.Process == nil {
		sw.Logger().Warn("slurmd not running — attempting restart")
		return sw.startSlurmd()
	}
	if err := sw.slurmdCmd.Process.Signal(syscall.Signal(0)); err != nil {
		sw.Logger().Warnf("slurmd process died: %v — restarting", err)
		sw.slurmdCmd.Wait()
		sw.slurmdCmd = nil
		return sw.startSlurmd()
	}
	return nil
}

// writeClientConfig writes a minimal /etc/slurm/slurm.conf sufficient for SLURM client
// tools (squeue, sbatch, sinfo, scancel) to locate and authenticate with slurmctld.
// slurmd fetches its full running config via --conf-server, so no NodeName/partition
// entries are needed here — they live only on the controller.
func (sw *SLURMWorker) writeClientConfig() error {
	conf := fmt.Sprintf(`# SLURM client config — auto-generated by Cluster-OS (worker node)
# slurmd uses --conf-server to fetch the authoritative config from slurmctld.
# This file is only used by client commands: squeue, sbatch, sinfo, etc.
ClusterName=cluster-os
SlurmctldHost=%s
SlurmctldPort=6817
AuthType=auth/munge
CryptoType=crypto/munge
AccountingStorageType=accounting_storage/none
`, sw.controllerIP)

	return os.WriteFile("/etc/slurm/slurm.conf", []byte(conf), 0644)
}

func (sw *SLURMWorker) startSlurmd() error {
	// Use --conf-server so slurmd fetches the authoritative config from slurmctld.
	// This avoids the NodeName=localhost problem: slurmd registers itself with its
	// actual hostname/IP, which must match a NodeName entry in the controller's config
	// (populated by the leader's Serf watcher).
	confServer := fmt.Sprintf("%s:6817", sw.controllerIP)
	args := []string{"-D", "--conf-server", confServer}

	// -N overrides the node name slurmd registers as. Use the Tailscale/LAN IP so it
	// matches the NodeAddr the controller sees in Serf member addresses.
	nodeName := sw.nodeIP
	if nodeName == "" {
		nodeName, _ = os.Hostname()
	}
	args = append(args, "-N", nodeName)

	cmd := exec.Command("slurmd", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Start(); err != nil {
		return fmt.Errorf("start slurmd: %w", err)
	}
	sw.slurmdCmd = cmd
	sw.Logger().Infof("slurmd started (PID %d, conf-server=%s, node=%s)", cmd.Process.Pid, confServer, nodeName)
	return nil
}

func (sw *SLURMWorker) stopSlurmd() error {
	if sw.slurmdCmd == nil || sw.slurmdCmd.Process == nil {
		return nil
	}
	sw.slurmdCmd.Process.Signal(os.Interrupt)
	done := make(chan error, 1)
	go func() { done <- sw.slurmdCmd.Wait() }()
	select {
	case <-done:
	case <-time.After(10 * time.Second):
		sw.slurmdCmd.Process.Kill()
		<-done
	}
	sw.slurmdCmd = nil
	sw.SetRunning(false)
	return nil
}
